[package]
name = "unsized_struct_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wtools = { version = "0.1.9", features = [ "nightly" ] }
