[package]
name = "former_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
name = "former_derive"
path = "../../../rust/former/derive/mod.rs"

[dev-dependencies]
trybuild = { version = "1.0.52", features = ["diff"] }

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.32"
quote = "1.0.10"
syn = {version = "1.0.81", features = ["full", "extra-traits", "parsing"] }
unzip-n = "0.1.2"
