[package]
name = "problem_trait_fn_implementing_trait"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "main4"
path = "src/main4.rs"

[dependencies]
